### ISSUE TITLE
Hyperopt

### ISSUE THREAD

**Issue by MrHumanRebel** [terrah27/freqtrade_strategies#1]
Hi!

I get this error when hyperopting:

Unexpected error 'NoneType' object has no attribute 'get_analyzed_dataframe' calling <bound method RAD.custom_stoploss of <RAD.RAD object at 0x7fc22a304eb0>>
Traceback (most recent call last):
  File "/home/trade/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/home/trade/freqtrade/user_data/strategies/rad_testing.py", line 60, in custom_stoploss
    dataframe, last_updated = self.dp.get_analyzed_dataframe(pair=pair,
AttributeError: 'NoneType' object has no attribute 'get_analyzed_dataframe'
Unexpected error 'NoneType' object has no attribute 'get_analyzed_dataframe' calling <bound method RAD.custom_stoploss of <RAD.RAD object at 0x7fd222425f10>>
Traceback (most recent call last):
  File "/home/trade/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/home/trade/freqtrade/user_data/strategies/rad_testing.py", line 60, in custom_stoploss
    dataframe, last_updated = self.dp.get_analyzed_dataframe(pair=pair,
AttributeError: 'NoneType' object has no attribute 'get_analyzed_dataframe'
Unexpected error 'NoneType' object has no attribute 'get_analyzed_dataframe' calling <bound method RAD.custom_stoploss of <RAD.RAD object at 0x7f9e15b47070>>
Traceback (most recent call last):
  File "/home/trade/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/home/trade/freqtrade/user_data/strategies/rad_testing.py", line 60, in custom_stoploss
    dataframe, last_updated = self.dp.get_analyzed_dataframe(pair=pair,
AttributeError: 'NoneType' object has no attribute 'get_analyzed_dataframe'
Unexpected error 'NoneType' object has no attribute 'get_analyzed_dataframe' calling <bound method RAD.custom_stoploss of <RAD.RAD object at 0x7f599c5e4fd0>>
Traceback (most recent call last):
  File "/home/trade/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/home/trade/freqtrade/user_data/strategies/rad_testing.py", line 60, in custom_stoploss
    dataframe, last_updated = self.dp.get_analyzed_dataframe(pair=pair,
AttributeError: 'NoneType' object has no attribute 'get_analyzed_dataframe'
Unexpected error 'NoneType' object has no attribute 'get_analyzed_dataframe' calling <bound method RAD.custom_stoploss of <RAD.RAD object at 0x7f6371c89f10>>
Traceback (most recent call last):
  File "/home/trade/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/home/trade/freqtrade/user_data/strategies/rad_testing.py", line 60, in custom_stoploss
    dataframe, last_updated = self.dp.get_analyzed_dataframe(pair=pair,
AttributeError: 'NoneType' object has no attribute 'get_analyzed_dataframe'

2021-04-26 16:45:06,463 - freqtrade - ERROR - 'NoneType' object has no attribute 'get_analyzed_dataframe'

Thanks for the help :D

**Comment by terrah27** [comment]
The error is coming from line 60 - which should only be hitting that option in dry/live run.  It looks like the hyperopt condition in the if statement isn't catching.  You could try switching the logic on the if/else or just commenting out the live run logic to force it to chose the hyperopt condition.
